### ISSUE TITLE
Mac support and signing

### ISSUE THREAD

**Issue by bmiller** [3ll3d00d/beqdesigner#219]
Hi,

It looks like the Mac build is running correctly for people.  I'll give you a PR soon for it.  It's mainly just adding in the mac .spec and .icns.  I think the only actually code change was that I changed the default theme to beq_dark from "default".  I figured it made sense to give everyone the color scheme out of the box that matches what's being posted in the BEQ thread.  We can dump it if you don't like that idea.  I've actually wondered if I should set all of the defaults for the spectrum and report generation to be the same values that Aron is using.   

There's a couple items I want to check off with you before doing the PR:
First, the app needs to be code signed so that the user doesn't get prompted with "it's from an unknown source" and then have to jump through a couple hoops.  I'm assuming that it'll be ok with you for me to generate the cert for it and then sign it but I wanted to make sure first.  I can send you a .p12 of it and the key if you'd like. 

Second, the only issue I know of is a rendering bug that I haven't solved yet.  The screens don't always redraw when there's a state change.  Like in the main window when you collapse/uncollapse the bottom pane it doesn't draw correctly. Switching out of the window and back in causes it to refresh correctly.  It's similar to 
https://github.com/3ll3d00d/beqdesigner/issues/56 from awhile back. It might be the same root cause. I haven't been able to find anything on it yet.  Do you have any ideas?  I'm thinking it might be a bug with either Qt or PyQt5. 

And finally, how would you like to handle distributing the binary?  I can rebuild it anytime you release a new one for windows.  That's simple for me to do now.  We'll just have a time zone lag depending on when you do it (I'm in Phoenix, I think -7 from you).

**Comment by 3ll3d00d** [comment]
Well I guess the q re distribution is more for you given that you have signed it though I know nothing about osx code signing and I am assuming it is visibly and irrevocably signed by you when I say that. Is it? If so, are you ok to allow it to be published somewhere? Somewhere being this repo releases page that is (which i have been using simply because it is a simple, free, easily accessible place to store relatively large binaries)

**Comment by 3ll3d00d** [comment]
Re the refresh, must surely be a Qt issue though is it only the graph panes that have this issue? If so that is a sign of a certain event not reaching the relevant matplotlib event handler (which implies something else is stealing/swallowing the event).

**Comment by bmiller** [comment]
Re: refresh it's not the graphs, they usually work correctly.  It's usually happens with the Qt widgets when they change state.  Stuff like a button being enabled, the split view on the man window opening/closing, labels if their string changes, etc.  That's why I'm thinking it's a Qt issue but I'm still pretty new with the framework.  So I figured it was worth asking if you had an idea.  

For distribution I have no problems with signing it and it being distributed here.  I was mainly making sure that you didn't have an issues with me creating the certs and doing it.  I assumed you wouldn't but it's the type of thing that I normally check.  My contracting years taught me to ask on them since some clients got really weird about. 

How would you like to handle getting the binaries?  I'm thinking I can either just post them on my fork and you can move them over or do something like DropBox for you to grab it from.

**Comment by 3ll3d00d** [comment]
This bug perhaps? https://bugreports.qt.io/plugins/servlet/mobile#issue/QTBUG-68521

Which Qt version do you have?

**Comment by 3ll3d00d** [comment]
https://www.google.com/amp/s/successfulsoftware.net/2018/11/02/qt-is-broken-on-macos-right-now/amp/ says 5.12 is a big improvement

**Comment by 3ll3d00d** [comment]
re the binaries, one option is to create an organisation for the beq repos and then you could edit the releases directly yourself

**Comment by bmiller** [comment]
I'll take a look at that bug when I get home, about to leave the office.  

For Qt I have have 5.11.3 installed.  I tried 5.12 over the weekend and it caused all of the qtawesome based icons to not render correctly.  As soon as I reverted back they all worked again.  I went with having the screen redraw issue since a quick window switch is a simple work around instead of not know what any button does.  :)

**Comment by 3ll3d00d** [comment]
Annoying, seems to be specific to pyqt as well - https://www.riverbankcomputing.com/pipermail/pyqt/2019-February/041376.html

Can't change to Qt for Python yet either as one of the other libs does not support it

**Comment by bmiller** [comment]
Nice, at this point sticking with 5.11.3 is the best bet until it's fixed for qtawesome.  The app is almost unusable outside of the very basics with qtawesome broken. I tried using it with 5.12 and it was really unpleasant.  

Since it looks like 5.12 fixes the screen refresh issues I'm seeing on mac, I'm going to leave things as is for a little bit to see if we get either a Qt or qtawesome update to fix that.  From the links you gave earlier it sounds like adding repaint() calls all over the place will fix the mac issue but I'd rather not muddy up the code with them if we end up being able to upgrade the libs soon.  It's easy enough to work around for the few mac users right now.

**Comment by 3ll3d00d** [comment]
@bmiller https://github.com/spyder-ide/qtawesome/issues/113 is now fixed in qtawesome 0.5.7 so I have updated the min versions in the pipfile according (in the above commit), can you try updating your deps to see if Qt behaves itself on osx now?

**Comment by bmiller** [comment]
I'll try to take a look at it tonight along with squashing the PR that's open.  I've been swamped the last couple weeks and haven't had a time to get back to it yet.

**Comment by bmiller** [comment]
@3ll3d00d I updated everything and it's mostly behaving itself now.  The qtawesome issues with not drawing the icons are gone and some of the mac redrawing issues appear to be working now from a quick test.  Buttons are activating like they should which was the big headache.   So much improvement over the last time I tried updating PyQT5.  

The main issue I'm still seeing in my quick run through is with the main window redrawing when the bottom panel is opened and closed.  It's acting a little better then before but still not 100%.  It's easy to work around by toggling in and out of the window.  So it looks like QT is making progress with their bug fixes.
