### ISSUE TITLE
Feature Request: Straight to file Peak Spectrum Generation

### ISSUE THREAD

**Issue by Mobe1969** [3ll3d00d/beqdesigner#438]
Can we have the option for a straight to file Peak Spectrum generation? The heat map generation is the most time consuming part of producing the filters. It is particularly hard with the tv series I do with the concatenated waves as if for example  I lose remote connection on generation, when I reestablish connection it causes a screen res glitch, and it regenerates again. Then when I finally get to save it to file, if I lose connection again I've got the same regeneration issue again. It can take well over an hour.

Thanks

**Comment by 3ll3d00d** [comment]
I don't expect this to be possible, the files are created by saving the rendered image so if there is no image rendered then there is nothing to save. I'm not aware of a way to do offscreen rendering either. I'll have another look into it to be sure though.

**Comment by 3ll3d00d** [comment]
0.10.3 adds a bit of logging around how long this takes

if you open the log window (CTRL+L) alongside the analysis window and then draw a heatmap, you should see logs like this

![image](https://user-images.githubusercontent.com/2487509/146636315-ff8a23d4-e6b1-40e2-a1dc-a1aa2c8821e4.png)

leave that dialog open and do something that makes the screen glitch, do you see it print this info again or not?

pls then cut and paste that logging to this issue and we'll see how long it takes and what causes the time

I particularly need to know if the logging is printed every single time it takes time to redraw (I suspect it won't)

**Comment by Mobe1969** [comment]
Would those logs exist in a file from my sessions yesterday? Or do I need to redo some?

**Comment by 3ll3d00d** [comment]
You would need to redo using this version https://github.com/3ll3d00d/beqdesigner/releases/tag/0.10.3

**Comment by Mobe1969** [comment]
here you go
[log.txt](https://github.com/3ll3d00d/beqdesigner/files/7740035/log.txt)

**Comment by 3ll3d00d** [comment]
did the chart redraw multiple times or just once?

is that a full bandwidth file? or I see it is episodes 1-16 so does that mean you have a single decimated file that contains ~17.4hrs of audio? i.e. those 16 episodes back to back

I can see some of those steps are extraordinarily slow, e.g. if you look at my example l_data_processed was 114ms whereas it is 353 *seconds* for you, i.e. 6 minutes. 

How much RAM does your computer have?

**Comment by Mobe1969** [comment]
That log I think it drew twice. Yes a 17 hour track.
I think 8gb.

I might have been unclear in my request. I don't care if it takes 1 hour to generate, but I do care that I have to stupidly generate it several times just to get a picture file. My target is a single picture file. The other two to 5 regenerations for the form display are a waste of everyone's time. You could stick a picture onscreen of a rubber duck and that would be as much use to meas the screen version of the heat map. I can always look at the image output to see it. I don't need it regenerates at some other resolution for a screen display.

**Comment by 3ll3d00d** [comment]
The app calculates it once and once only, the rest of it is due to your machine and whatever your monitor is doing (and how that causes windows and/or Qt to redraw). I have zero control over this. 

As I said before, the file **is** the image displayed on screen so no pic on screen == no file. Changing this would require completely changing how these are generated which will almost certainly mean new heatmaps look very different to old ones. I know of no way to avoid this.

As to the time it takes, the timing says your machine does not have enough RAM to deal with files of that size. Your choices are to cut them into separate files and create >1 picture or get more RAM.

**Comment by 3ll3d00d** [comment]
I've found something that might help with the redraws depending on when they are triggered, the next build will have the toggle button. Once you press it, the chart will disappear from view so it should mean that any redraw (e.g. caused by the OS) costs nothing. The file can still be exported and it will be sized at whatever size the chart was at the point you pressed the button. Press it again to show the chart if you want to resize. This will be in the next build.

![image](https://user-images.githubusercontent.com/2487509/146672141-4dfed94e-1fa4-48a8-8468-87b09af09695.png)

**Comment by Mobe1969** [comment]
Ok no worries. I was just wishing forlornly that there was some way to top wasting my time generating screen shots as an interior step to get an image file. 

After doing this needless duplication and triplication over 5000 times, I thought I'd ask.

**Comment by 3ll3d00d** [comment]
getting more RAM will make a massive difference though, I made ~17hr decimated wav file for comparison

the machine I'm running on has 32G and loading this file & analysing it consumed a peak of ~18G of RAM. You can see processing time was only a few seconds. I don't know whether it is an option for you but at least this gives an idea of the time you'd save.

```
2021-12-19 10:55:43,466 - INFO - MainThread	- signal - __init__ - Split o into 3 segments of length 20046882
2021-12-19 10:55:58,996 - INFO - MainThread	- signal - __init__ - Split T into 3 segments of length 20046882
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,start,l_axes_init,19.5
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,l_axes_init,l_data_loaded,0.0
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,l_data_loaded,l_data_processed,2176.9
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,l_data_processed,l_data_plotted,38.0
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,l_data_plotted,l_limits,2.1
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,l_limits,r_data_loaded,0.0
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,r_data_loaded,r_data_processed,2122.8
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,r_data_processed,r_data_plotted,33.8
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,r_data_plotted,r_limits,24.7
2021-12-19 10:56:38,848 - INFO - MainThread	- analysis - __log_times - Heatmap,r_limits,cb,12.6
2021-12-19 10:58:07,269 - INFO - MainThread	- root - change_level - Changing log level from INFO to INFO
```

**Comment by Mobe1969** [comment]
Cheers. Yeah I'll see if I can get different ram. I really don't. Have a need to upgrade outside of BEQ.

**Comment by 3ll3d00d** [comment]
I've pushed another change which should arrive in 0.10.5, you can use ctrl+alt+shift+c to open the heatmap dialog without opening the waveform view. On my test, this cuts the ram used by the app down to 5G. Open task manager and keep an eye on the RAM used by beqd when you open such a file, let me know the amount used for the above file. Hopefully this quick change is sufficient to get it to fit in your available RAM.

**Comment by 3ll3d00d** [comment]
the above is building now, should be available at https://github.com/3ll3d00d/beqdesigner/releases/tag/0.10.5 in 5-10mins

**Comment by Mobe1969** [comment]
Nice! Thanks. I'll try it with the prior waveform.

**Comment by Mobe1969** [comment]
Ok thanks it is working, especially the shortcut bypassing the waveform.

I don't quite get the whole screen dependency, but in line with that, is that why the heat map sizes for two different movies are never the same dimension? They all vary aspect ratio?  Because it is linked to the width of the left hand side because that isn't fixed, and the width of that depends on the name of the signal file? Is there any reason the side panel isn't fixed width?

Cheers

**Comment by 3ll3d00d** [comment]
>  Is there any reason the side panel isn't fixed width?

because I'd never noticed it before you just mentioned it :) (and also because doing any gui layout work is a fiddly PITA)

practically speaking fixing the size would mean moving the dropdowns out of that dialog so the chart is always the same size for a given dialog window size

i don't think there is any other reason why the dimensions of the chart itself should vary, the contents might vary depending on how big the axis labels are though

**Comment by 3ll3d00d** [comment]
split that to a new issue btw hence closing this one
